title: Default Page

tabs:
  content:
    label: Contenu
    icon: text
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              layout:
                type: layout
                layouts:
                  - "1/1"
                  - "1/2, 1/2"
                  - "1/3, 2/3"
                  - "2/3, 1/3"
                fieldsets:
                  - heading
                  - text
                  - largeText
                  - image
                  - faq
      sidebar:
        width: 1/3
        sections:
          sideContent:
            type: fields
            fields:
              toggleHeader:
                label: Afficher header
                type: toggle
                text:
                  - "non"
                  - "oui"
              imageHeader:
                type: files
                multiple: false
              intro:
                type: text



  seo:
    label: SEO
    icon: search
    fields:
      seoTitle:
        label: Titre SEO
        type: text
      seoDescription:
        label: Description SEO
        type: text

