title: Default Page

tabs:
  content:
    label: Contenu
    icon: text
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
      sidebar:
        width: 1/3
        sections:
          


  seo:
    label: SEO
    icon: search
    fields:
      seoTitle:
        label: Titre SEO
        type: text
      seoDescription:
        label: Description SEO
        type: text

